### ISSUE TITLE
option to include photo gallery for past symposia

### ISSUE THREAD

**Issue by jurgenvinju** [cwi-nl/sen-symposium#7]
something like: https://dmnfarrell.github.io/software/jekyll-galleries

we have many photos from 2022. could be nice to show them? What do you think?

**Comment by feitosa-daniel** [comment]
I used a similar plugin for the [VERSEN honorary members page](http://www.versen.nl/contents/honorary-members). Would something like this work?

**Comment by jurgenvinju** [comment]
yes!

**Comment by feitosa-daniel** [comment]
Great! De we create a dedicated menu entry for photos (of all years) or do we add a link to 2022's photos in the [history page](http://www.sen-symposium.nl/history/) once 2022 edition's program is stored there?

**Comment by jurgenvinju** [comment]
I dunno. What do you think?

**Comment by feitosa-daniel** [comment]
I would go for a link on the history page. I think the photos are mainly for the attendants to browse and collect some memories :-).

**Comment by jurgenvinju** [comment]
ok let's do that

**Comment by jurgenvinju** [comment]
Great!
